xylonfb-y := xylonfb_main.o xylonfb_core.o xylonfb_ioctl.o xylonfb_pixclk.o

xylonfb-$(CONFIG_FB_XYLON_MISC) += xylonfb_misc.o
xylonfb-$(CONFIG_FB_XYLON_MISC_ADV7511) += xylonfb_adv7511.o
obj-$(CONFIG_FB_XYLON_MISC_ADV7511) += adv7511.o

obj-$(CONFIG_FB_XYLON) += xylonfb.o
